# Generated by Django 4.0.3 on 2022-05-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='created_by',
        ),
    ]
